#! /usr/bin/bash


current_db="$2"
if [[ $current_db == '' ]]; then
        echo -e "\033[30;41mError: Database is not selected, Sir!\033[0m"
        exit
fi


fullQuery=$1

read -ra words <<< "$fullQuery"
wordCount=${#words[@]}


if [[ ${words[0],,} == "drop" ]]
then
	if [[ ${words[1],,} == 'table' && wordCount -eq 3 ]]
	then
		exist=0
		tables=( $(find ./$current_db -maxdepth 1 -type f -printf "%f\n") )
		for table in ${tables[@]}
		do
			if [[ "${words[2],,}" == "${table,,}" ]]
			then
				exist=1
				break
			fi
		done
		if [[ exist -eq 1 ]]
		then
			rm "./$current_db/$table"
			rm "./$current_db/.$table"
			echo -e "\033[30;42mTable dropped successfully, Sir!\033[0m"
		else
			echo -e "\033[30;41mTable doesn't exist, Sir!\033[0m"
		fi
	else
		echo -e "\033[30;41mError: Check your Syntax, Sir!\033[0m"
	fi
else
	echo -e "\033[30;41mError: Check your Syntax, Sir!\033[0m"
fi





