#! /usr/bin/bash


current_db="$2"
if [[ $current_db == '' ]]; then
        echo -e "\033[30;41mError: Database is not selected, Sir!\033[0m"
        exit
fi

fullQuery=$1

read -ra words <<< "$fullQuery"
wordCount=${#words[@]}

if [[ ${words[0],,} == "show" ]]
then
	if [[ ${words[1],,} == 'tables' && wordCount -eq 2 ]]
	then
		tables=( $(find ./$current_db -maxdepth 1 -type f -printf "%f\n") )
		for table in ${tables[@]}
		do
			if [[ "${table,,}" == "." || "${table,,}" == ".." ]]
			then
				continue
			fi
			if [[ "$table" == *.* ]]; then
        		continue
    		fi
			echo -e "\033[30;104m$table\033[0m"
		done

		echo -e "\033[30;42mTables shown successfully, Sir!\033[0m"
	else
		echo -e "\033[30;41mError: Check your Syntax, Sir!\033[0m"
	fi

else
	echo -e "\033[30;41mError: Check your Syntax, Sir!\033[0m"
fi


