#!/bin/bash

fullQuery="$*"

read -ra words <<< "$fullQuery"
wordCount=${#words[@]}

database=0


if [[ ${words[0],,} == "show" ]]
then
	if [[ ${words[1],,} == "databases" &&  $wordCount -eq 2 ]]
	then
		exist=0
		dirs=( $(find . -maxdepth 1 -type d -printf "%f\n") )
		
		for dir in ${dirs[@]}
		do
			if [[ $dir != '.' ]]; then
			echo -e "\033[30;104m$dir\033[0m"
			fi
		done
		echo -e "\033[30;42mDatabases shown successfully, Sir!\033[0m"
	else
		echo -e "\033[30;41mError: Check your Syntax, Sir!\033[0m"
	fi
else
	echo -e "\033[30;41mError: Check your Syntax, Sir!\033[0m"
fi

